services:
  mysql:
    image: mysql:8.0
    container_name: pokekanri_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pokekanri
    ports:
      - "13306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
  elasticsearch:
    container_name: pokekanri_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    ports:
      - "19200:9200"
      - "19300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    memswap_limit: 2g
    cap_add:
      - IPC_LOCK
    volumes:
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data
volumes:
  mysql-data:
    driver: "local"
  elasticsearch-data:
    driver: "local"
