services:
  mysql:
    image: mysql:8.0
    container_name: pokekanri_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pokekanridb
    ports:
      - "13306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf
  elasticsearch:
    container_name: pokekanri_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    ports:
      - "19200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    platform: linux/amd64
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
    volumes:
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data
  kibana:
    container_name: pokekanri_kibana
    image: docker.elastic.co/kibana/kibana:8.15.3
    ports:
      - "15601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://pokekanri_elasticsearch:9200"
volumes:
  mysql-data:
    driver: "local"
  elasticsearch-data:
    driver: "local"
