// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"time"
)

type CardType struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Inventory struct {
	ID         int64     `json:"id"`
	UserID     string    `json:"user_id"`
	CardID     int64     `json:"card_id"`
	CardTypeID int64     `json:"card_type_id"`
	Quantity   int32     `json:"quantity"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Pokemon struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	EnergyType  string    `json:"energy_type"`
	ImageUrl    string    `json:"image_url"`
	Hp          int64     `json:"hp"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Trainer struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	TrainerType string    `json:"trainer_type"`
	ImageUrl    string    `json:"image_url"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
