// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
)

type Querier interface {
	CollectionFindByUserId(ctx context.Context, userID string) ([]CollectionFindByUserIdRow, error)
	DeleteCardFromInventory(ctx context.Context, id int64) error
	FindCardFromInventory(ctx context.Context, arg FindCardFromInventoryParams) (FindCardFromInventoryRow, error)
	InsertInventory(ctx context.Context, arg InsertInventoryParams) error
	InventoryFindByUserId(ctx context.Context, userID string) ([]Inventory, error)
	PokemonFindById(ctx context.Context, id int64) (Pokemon, error)
	TrainerFindById(ctx context.Context, id int64) (Trainer, error)
	UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) error
}

var _ Querier = (*Queries)(nil)
