// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
)

type Querier interface {
	InsertInventory(ctx context.Context, arg InsertInventoryParams) error
	PokemonFindById(ctx context.Context, id int64) (Pokemon, error)
	TrainerFindById(ctx context.Context, id int64) (Trainer, error)
}

var _ Querier = (*Queries)(nil)
